[package]
name = "eguard-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
regex = "1.11.2"
reqwest = { version="0.12.23", features=["json","rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
