/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JsEGuard {
  constructor(cfg: JsEGuardConfig)
  /** Pure check; no I/O. */
  isSecure(path: string, method: string): boolean
  /** Extract session id from cookie/header values provided by the caller. */
  extractSessionId(cookieHeader?: string | undefined | null, headerName?: string | undefined | null, headerValue?: string | undefined | null): string | null
  /** Asynchronous trust decision (calls your Sentry Cloud API). */
  decide(sessionId: string): Promise<unknown>
}

export interface JsDecision {
  allow: boolean
  status?: number
  message?: string
}

export interface JsEGuardConfig {
  apiBaseUrl: string
  apiKey: string
  secureRoutes: Array<JsSecureRoute>
  sessionExtraction: JsSessionExtraction
  /** JS numbers are 64-bit floats; use f64 at the boundary. */
  minTrustScore: number
  timeoutMs?: number
}

export interface JsSecureRoute {
  pathPattern: string
  methods?: Array<string>
}

export interface JsSessionExtraction {
  cookieName?: string
  headerName?: string
  headerBearer?: boolean
}
